import { NewsArticle } from '@/types';

export const sampleArticles: NewsArticle[] = [
  // {
  //   id: '1',
  //   title: 'Revolutionary AI Algorithm Predicts Protein Folding with 99% Accuracy',
  //   excerpt: 'A breakthrough in computational biology has led to the development of an AI system that can predict protein structures with unprecedented accuracy, potentially accelerating drug discovery by decades.',
  //   content: 'This is a detailed article about the revolutionary AI algorithm...',
  //   author: 'Dr. Sarah Chen',
  //   publishedAt: '2024-01-15T10:00:00Z',
  //   updatedAt: '2024-01-15T10:00:00Z',
  //   imageUrl: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800&h=600&fit=crop',
  //   category: 'AI',
  //   tags: ['Machine Learning', 'Protein Folding', 'Drug Discovery', 'Computational Biology'],
  //   readTime: 8,
  //   featured: true,
  //   slug: 'revolutionary-ai-algorithm-protein-folding',
  // },
  // {
  //   id: '2',
  //   title: 'CRISPR Gene Editing Breakthrough: New Technique Eliminates Off-Target Effects',
  //   excerpt: 'Scientists have developed a novel CRISPR-Cas9 variant that virtually eliminates off-target effects, bringing us closer to safe and effective gene therapy treatments.',
  //   content: 'This is a detailed article about the CRISPR breakthrough...',
  //   author: 'Prof. Michael Rodriguez',
  //   publishedAt: '2024-01-14T14:30:00Z',
  //   updatedAt: '2024-01-14T14:30:00Z',
  //   imageUrl: 'https://images.unsplash.com/photo-1576086213369-97a306d36557?w=800&h=600&fit=crop',
  //   category: 'Biotechnology',
  //   tags: ['CRISPR', 'Gene Editing', 'Gene Therapy', 'Precision Medicine'],
  //   readTime: 12,
  //   featured: true,
  //   slug: 'crispr-gene-editing-breakthrough-off-target-effects',
  // },
  // {
  //   id: '3',
  //   title: 'Startup Raises $50M for AI-Powered Drug Discovery Platform',
  //   excerpt: 'A biotech startup has secured significant funding to develop an AI platform that can identify potential drug candidates in days rather than years.',
  //   content: 'This is a detailed article about the startup funding...',
  //   author: 'Alex Thompson',
  //   publishedAt: '2024-01-13T09:15:00Z',
  //   updatedAt: '2024-01-13T09:15:00Z',
  //   imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop',
  //   category: 'Startup',
  //   tags: ['Funding', 'Drug Discovery', 'AI Platform', 'Biotech Startup'],
  //   readTime: 5,
  //   featured: false,
  //   slug: 'startup-raises-50m-ai-powered-drug-discovery',
  // },
  // {
  //   id: '4',
  //   title: 'New Biomaterial Shows Promise for Regenerative Medicine',
  //   excerpt: 'Researchers have developed a novel biomaterial that can promote tissue regeneration and accelerate wound healing in clinical trials.',
  //   content: 'This is a detailed article about the new biomaterial...',
  //   author: 'Dr. Emily Watson',
  //   publishedAt: '2024-01-12T16:45:00Z',
  //   updatedAt: '2024-01-12T16:45:00Z',
  //   imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&h=600&fit=crop',
  //   category: 'Research',
  //   tags: ['Biomaterials', 'Regenerative Medicine', 'Tissue Engineering', 'Wound Healing'],
  //   readTime: 10,
  //   featured: false,
  //   slug: 'new-biomaterial-regenerative-medicine',
  // },
  {
    id: '5',
    title: 'AI-Powered Diagnostic Tool Detects Cancer Earlier Than Ever Before',
    excerpt: 'A new AI diagnostic system has demonstrated the ability to detect multiple types of cancer at stages previously undetectable by conventional methods.',
    content: 'This is a detailed article about the AI diagnostic tool...',
    author: 'Dr. James Kim',
    publishedAt: '2024-01-11T11:20:00Z',
    updatedAt: '2024-01-11T11:20:00Z',
    imageUrl: './randomimage.jpeg',
    category: 'AI',
    tags: ['Cancer Detection', 'Early Diagnosis', 'Medical AI', 'Precision Medicine'],
    readTime: 7,
    featured: false,
    slug: 'ai-powered-diagnostic-tool-cancer-detection',
  },
  // {
  //   id: '6',
  //   title: 'Synthetic Biology Breakthrough: Engineered Bacteria Produce Novel Antibiotics',
  //   excerpt: 'Scientists have successfully engineered bacteria to produce entirely new classes of antibiotics, offering hope in the fight against antibiotic resistance.',
  //   content: 'This is a detailed article about the synthetic biology breakthrough...',
  //   author: 'Prof. Lisa Park',
  //   publishedAt: '2024-01-10T13:10:00Z',
  //   updatedAt: '2024-01-10T13:10:00Z',
  //   imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&h=600&fit=crop',
  //   category: 'Innovation',
  //   tags: ['Synthetic Biology', 'Antibiotics', 'Antibiotic Resistance', 'Genetic Engineering'],
  //   readTime: 9,
  //   featured: false,
  //   slug: 'synthetic-biology-breakthrough-engineered-bacteria-antibiotics',
  // },
];
